version: '3.4'

volumes:
  productdata:

networks:
  frontend:
  backend:

services:
  mysql:
    image: 'arm64v8/mysql:8.0.34'
    volumes:
      - productdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
      - bind-address=0.0.0.0

  dbinit:
    build:
      context: .
      dockerfile: Dockerfile.simple
    networks:
      - backend
    environment:
      - INITDB=true
      - DBHOST=mysql
    depends_on:
      - mysql

  mvc:
    build:
      context: .
      dockerfile: Dockerfile.simple
    networks:
      - backend
      - frontend
    volumes:
      - ~/.aspnet/https:/https:ro
#      - ./Certs:/https:ro
#      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
#    ports:
#      - 8000:80
#      - 8001:443
    environment:
      - DBHOST=mysql
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MySecurePwd1@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/exampleapp.pfx 
    depends_on:
      - mysql

  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:8080
#      - 3001:443
    depends_on:
      - mvc
    networks:
      - frontend
    links:
      - mvc
